Update packages

diff --git a/packages/os-specific/athena-config/usr/bin/shell-rocket b/packages/os-specific/athena-config/usr/bin/shell-rocket
--- a/packages/os-specific/athena-config/usr/bin/shell-rocket
+++ b/packages/os-specific/athena-config/usr/bin/shell-rocket
@@ -6,10 +6,11 @@
 Help()
 {
    # Display Help
-   echo "$(basename "$0") [-b <binary>] [-d <directory>] [-g] [-h] [-p <package>] [-r] [-x <args>]"
+   echo "$(basename "$0") [-b <binary>] [-c <command>] [-d <directory>] [-g] [-h] [-p <package>] [-r] [-x <args>]"
    echo
    echo "Options:"
    echo "-b     Specify the binary to launch."
+   echo "-c     Specify the command to launch."
    echo "-d     Specify the directory to land."
    echo "-g     Set if launching a GUI application."
    echo "-h     Print this Help."
@@ -22,6 +23,7 @@ Help()
    echo "$(basename "$0") -b msfconsole -p metasploit"
    echo "$(basename "$0") -b nmap"
    echo "$(basename "$0") -b seclists -d /usr/share/payloads/seclists"
+   echo "$(basename "$0") -c \"echo \"Disconnecting all VPN sessions...\";sudo killall openvpn\""
    echo
 }
 
@@ -29,10 +31,13 @@ Help()
 # Process the input options. Add options as needed.        #
 ############################################################
 # Get the options
-while getopts ":b:d:ghp:rx:" option; do #When using getopts, putting : after an option character means that it requires an argument (i.e., 'i:' requires arg).
+while getopts ":b:c:d:ghp:rx:" option; do #When using getopts, putting : after an option character means that it requires an argument (i.e., 'i:' requires arg).
    case "${option}" in
       b) 
          binary=$OPTARG
+         ;;
+      c)
+         command=$OPTARG
          ;;
       d)
          directory=$OPTARG
@@ -63,9 +68,8 @@ while getopts ":b:d:ghp:rx:" option; do #When using getopts, putting : after an 
    esac
 done
 
-echo
-if [ ! "$binary" ]; then
-    echo "Error: no binary specified."
+if [ $# -eq 0 ]; then
+    echo "Error: no arguments provided."
     echo
     Help >&2
     exit 0
@@ -79,54 +83,62 @@ if [[ "$TERMINAL_EXEC" =~ "terminator" || "$TERMINAL_EXEC" =~ "terminology" || "
   TERMINAL_EXEC="kitty -e"
 fi
 
-# Search for application
-if [ ! "$(command -v "$binary")" ] && [[ ! -d $directory ]]; then
-  if [ -n "$pkg" ]; then
-    if [[ -n "$NO_REPETITION" ]]; then
-      echo "$binary is not installed. Installing..."
-      sudo pacman -S "$pkg"
+if [[ -z "$command" ]]; then
+  # Search for application
+  if [ ! "$(command -v "$binary")" ] && [[ ! -d $directory ]]; then
+    if [ -n "$pkg" ]; then
+      if [[ -n "$NO_REPETITION" ]]; then
+        echo "$binary is not installed. Installing..."
+        sudo pacman -S "$pkg"
+      else
+        NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "echo \"$binary is not installed. Installing...\" && sudo pacman -S $pkg |& tee $temp_file;if grep -q "error:" "$temp_file"; then $SHELL;fi"
+      fi
     else
-      NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "echo \"$binary is not installed. Installing...\" && sudo pacman -S $pkg |& tee $temp_file;if grep -q "error:" "$temp_file"; then $SHELL;fi"
+      if [[ -n "$NO_REPETITION" ]]; then
+        echo "$binary is not installed. Installing..."
+        sudo pacman -S "$binary"
+      else
+        NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "echo \"$binary is not installed. Installing...\" && sudo pacman -S $binary |& tee $temp_file;if grep -q "error:" "$temp_file"; then $SHELL;fi"
+      fi
     fi
-  else
-    if [[ -n "$NO_REPETITION" ]]; then
-      echo "$binary is not installed. Installing..."
-      sudo pacman -S "$binary"
-    else
-      NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "echo \"$binary is not installed. Installing...\" && sudo pacman -S $binary |& tee $temp_file;if grep -q "error:" "$temp_file"; then $SHELL;fi"
+
+    install_output=$(<"$temp_file")
+    rm "$temp_file"
+    # Check the output of the installation command for any error messages indicating a failure
+    # Message printed on the calling terminal, not on the invoked one
+    if echo "$install_output" | grep -q "error:"; then
+        echo "Failed to install $binary. $binary package not found. Check if the binary has a different package name and use -p argument to specify it."
+        exit 1
     fi
   fi
 
-  install_output=$(<"$temp_file")
-  rm "$temp_file"
-  # Check the output of the installation command for any error messages indicating a failure
-  # Message printed on the calling terminal, not on the invoked one
-  if echo "$install_output" | grep -q "error:"; then
-      echo "Failed to install $binary. $binary package not found. Check if the binary has a different package name and use -p argument to specify it."
-      exit 1
+  if [[ "$root" ]] && [[ ! "$guiapp" ]]; then
+    binary="echo '$binary requires root permission...';sudo $binary"
+  elif [[ "$root" ]] && [[ "$guiapp" ]]; then
+    binary=(pkexec "$binary")
   fi
-fi
 
-if [[ "$root" ]] && [[ ! "$guiapp" ]]; then
-  binary="echo '$binary requires root permission...';sudo $binary"
-elif [[ "$root" ]] && [[ "$guiapp" ]]; then
-  binary=(pkexec "$binary")
-fi
+  if [[ -n "$args" ]]; then
+    binary+=" $args"
+  fi
 
-if [[ -n "$args" ]]; then
-  binary+=" $args"
-fi
-
-if [[ -z "$directory" ]]; then
-  if [[ -n "$NO_REPETITION" ]] || [[ "$guiapp" ]]; then
-    "${binary[@]}"
+  if [[ -z "$directory" ]]; then
+    if [[ -n "$NO_REPETITION" ]] || [[ "$guiapp" ]]; then
+      "${binary[@]}"
+    else
+      NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "$binary;$SHELL"
+    fi
   else
-    NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "$binary;$SHELL"
+    if [[ -n "$NO_REPETITION" ]]; then
+      cd $directory;$SHELL
+    else
+      NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "cd $directory;$SHELL"
+    fi
   fi
 else
-  if [[ -n "$NO_REPETITION" ]]; then
-    cd $directory;$SHELL
-  else
-    NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "cd $directory;$SHELL"
-  fi
+    if [[ -n "$NO_REPETITION" ]]; then
+      "${command[@]}"
+    else
+      NO_REPETITION=1 $TERMINAL_EXEC /usr/bin/bash -c "$command;$SHELL"
+    fi
 fi
