Update hephaestus

diff --git a/packages/hephaestus b/packages/hephaestus
--- a/packages/hephaestus
+++ b/packages/hephaestus
@@ -66,7 +66,7 @@ find_pkgbuild_dirs() {
 }
 
 sign_package() {
-    #* If env $sign is false, do not add sign packages
+    #* If env $sign is false, do not sign packages
     if [[ "$sign" ]]
     then
         echo "Signing the package..."
@@ -119,12 +119,32 @@ build_package() {
     cd $src_dir
 }
 
+printf '%b\n' "$(base64 -d <<<"H4sIAAAAAAAAA6VRWwqAMAz79xR+ahF3Am8yqAfp4W36Yn4IopGFJjbdxoiO7yCaRGaA2VfhJp5ckcg3/3wKGCJqN8BsLSm0yDx8DOC5N+wx8lk2g2Inl5G3PmX/XS1Zq72gYXWtK2Tkw+02cgeXsYVth++cnt9luH+imf0amqd/73cBIZJnZ/8BAAA=" | gunzip)" #User printf for colored output
+echo
+echo "The Athena OS CI/CD Builder"
+echo
+
 # Parse command-line options
-while getopts "hs" opt; do
+while getopts "dhrs" opt; do
     case $opt in
+        d)  
+            db=true
+            ;;
         h)
-            echo "Usage: $0 [-s] [package1 package2 ...]"
+            echo "Usage: $0 [-d] [-r] [-s] [package1 package2 ...]"
             exit 0
+            ;;
+        r)
+            rsync=true
+            if [[ -z "${SSH_PASSPHRASE}" || -z "${REPOSITORY_SERVER}" ]]; then
+                if [[ -z "${SSH_PASSPHRASE}" ]]; then
+                    echo "Error -r argument: Missing 'SSH_PASSPHRASE' environment variable passed as container argument."
+                fi
+                if [[ -z "${REPOSITORY_SERVER}" ]]; then
+                    echo "Error -r argument: Missing 'REPOSITORY_SERVER' environment variable passed as container argument."
+                fi
+                exit 1
+            fi
             ;;
         s)
             sign=true
@@ -158,6 +178,16 @@ for path in "${result[@]}"; do
     echo "Found PKGBUILD: $path"
     # Build and sign packages
     build_package "$(dirname $path)" "$cpu_arch" "$src_dir" "$out_dir"
+    echo
 done
+
+if [[ "$db" ]]
+then
+    repo-add --verify --sign -R $out_dir/athena.db.tar.gz $out_dir/*.pkg.tar.zst
+fi
+
+if [[ -n "$rsync" && -n "${SSH_PASSPHRASE}" && -n "${REPOSITORY_SERVER}" ]]; then
+    sshpass -p "${SSH_PASSPHRASE}" rsync -avzzlr --delete -e "ssh -p 1027 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" "$out_dir/" "${REPOSITORY_SERVER}"
+fi
 
 postbuild_command
